config/routes.rb
RecklooseQuotePortal::Application.routes.draw do
 
	devise_for :users
	root 'quotes#index'
	resources :quotes
	resources :questions
	resources :choices, only: [:create, :destroy, :update]


end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
end

app/models/choice.rb
class Choice < ActiveRecord::Base
	belongs_to :answer
	belongs_to :quote
end

app/models/question.rb
class Question < ActiveRecord::Base
	# attr_accessor :name, :answers_attributes	

	has_many :answers
	has_many :choices, :through => :answer
	accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	has_many :choices
	has_many :answers, :through => :choices

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :quotes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def is_admin?
	warden.authenticate!
		unless current_user && current_user.try(:admin?)
			render file: "errors#routing", status: :forbidden
		end
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :is_admin?
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit!
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    if current_user.try(:admin?)
      @quotes = Quote.all
    else
      @quotes = current_user.quotes
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    #@total = @quote.choices.map { |choice| choice.answer.value }.map { |answer| answer.value }.sum
    #@total = @quote.choices.map { |choice| choice.answer.value }.sum
    #@total = @quote.answers.map { |answer| answer.value }.sum
    @total = @quote.answers.map(&:value).sum
    # @question =Question.find(@quote.answers.question_id)
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    @questions = Question.all
    # @users = User.all
    # @answer = Answer.all
  end


  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
    @questions = Question.all
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    @quote.user = current_user

    params[:quote][:questions].each do |question_id, answer_id|
      @quote.choices << Choice.new(:answer_id => answer_id)
    end

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:questions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |builder|
	      render(association.to_s.singularize + "_fields", f: builder)
	    end
	    link_to(name, '#', class: "btn btn-primary add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  	end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=1000">
    <title><%= content_for?(:title) ? yield(:title) : "reckloose Website Quote Portal" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Size should be 32 x 32 pixels -->
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
  </head>
  <body>

<ul class="cb-slideshow">
    <li><span>reckloose</span><div></div></li>
    <li><span>reckloose</span><div></div></li>
    <li><span>reckloose</span><div></div></li>
    <li><span>reckloose</span><div></div></li>
    <li><span>reckloose</span><div></div></li>
    <li><span>reckloose</span><div></div></li>
</ul>

<div class="full-wrapper">
<header id="header">
  <div class="container-fluid">
    <div class="logo">
     <%= link_to image_tag("logo.png", :alt => "reckloose Entertainment on Facebook"), '/' %>
    </div><!-- Nav -->

    <nav id="nav">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/quotes/new">Create Quote</a></li>
        <% if user_signed_in? %>
          <li> <%= link_to 'Logout', destroy_user_session_path, :method => 'DELETE' %></li>
        <% else %>
          <li> <%= link_to 'SignUp', new_user_registration_path %></li>
          <li> <%= link_to 'Login', new_user_session_path %> </li>
        <% end %>
        <% if current_user.try(:admin?) %>
          <li><a href="/questions/">Questions</a></li>
        <% end %>




      </ul>
    </nav>
  </div><!--/.container-fluid -->
</header>

    <div class="container-fluid main">

      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to 'My Quotes', quotes_path %></li>
              <li><%= link_to 'Create Quote', new_quote_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
        <% if user_signed_in? %>
            <div class="well">Howdy, <strong><%= current_user.email %>!</strong></div>
        <% end %>
        
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

<footer class="footer">
<div class="container-fluid">


    <div class="row-fluid bottom">
      <div class="span8 block">
            
            <p>Website &copy; reckloose Entertainment <%= Time.now.year %><br />
        Website Designed by <a href="http://reckloose.com">reckloose Entertainment</a></p>
        
      </div>
      
      <div class="span4 block">
       <ul class="social-icons">
            <li><%= link_to image_tag("facebook.png", :alt => "reckloose Entertainment on Facebook"), '#' %></li>
            <li><%= link_to image_tag("twitter.png", :alt => "reckloose Entertainment on Twitter"), '#' %></li>
            <li><%= link_to image_tag("google.png", :alt => "reckloose Entertainment on Google Places"), '#' %></li>
        </ul>
    </div>
      
    </div>
    
</div>
</footer>
</div><!-- full-wrapper -->

 <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

</body>
</html>

app/views/questions/_answer_fields.html.erb
<fieldset>
	<div class="row-fluid">
		<div class="span6">
			<%= f.label :name, "Answer" %>
			<%= f.text_field :name %>
		</div>
		<div class="span6">
			<%= f.label :value, "Value Associated" %>
			<%= f.text_field :value %>
		</div>
	</div>
	<%= f.hidden_field :_destroy %>
	<%= link_to "Remove Answer", '#', class: "btn btn-danger remove_fields" %>
	<hr>

</fieldset>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

	<div class="row-fluid">
		<div class="span12">
			<div class="inputs">
				<%= f.input :name %>
			</div>
			<hr>
			<div>
				<%= f.fields_for :answers do |builder| %>
				  <%= render 'answer_fields', f: builder %>
				<% end %>
				<%= link_to_add_fields "Add Answer", f, :answers %>
			</div>
			
		</div>
	</div>

<hr>

	<div class="row-fluid">
		<div class="span4">
			<div class="actions">
				<%= button_tag(type: "submit", class: "btn btn-success btn-large") do %>
					    Create Question <i class="icon-share"></i>
				<% end %>
			</div>
		</div>
		<div class="span3">
			<%= link_to 'Exit Without Saving', @question, :class => "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
		</div>

<% end %>

app/views/questions/edit.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', questions_path, :class => "btn btn-inverse" %>

<div class="page-header">
  <h1>Editing question</h1>
</div>

<p class="lead">Add a question with answers and values.</p>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="page-header">
  <h1>Listing Questions <small>Create, Edit or Delete Questions</small></h1>
</div>

<p class="lead">This page is for administrators only. To edit questions for quotes.</p>

<%= link_to '<i class="icon-plus"></i> New Question '.html_safe, new_question_path, :class => "btn btn-large btn-success pull-left" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Show Question</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <td><%= link_to 'Show', question, :class => "btn btn-small" %></td>
        <td><%= link_to 'Edit', edit_question_path(question), :class => "btn btn-small btn-info" %></td>
        <td><%= link_to 'Delete', question, :class => "btn btn-small btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/questions/new.html.erb
<div class="page-header">
  <%= link_to 'Back', questions_path, :class => "btn btn-inverse" %>
  <h1>New Question</h1>
</div>

<p class="lead">Only administrators can create new questions.</p>

<%= render 'form' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', questions_path, :class => "btn btn-inverse" %>

<div class="page-header">
  <h1><%= @question.name %></h1>
</div>

<p class="lead">To edit this question click on the value you want to edit.</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Answer</th>
      <th>Value</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @question.answers.each do |answer| %>
      <tr>
        <td><%= answer.name %></td>
        <td><%= answer.value %></td>
        <td><%= link_to 'Edit', edit_question_path(@question) %></td>
      </tr>
    <% end %>

  </tbody>
</table> 
  

app/views/quotes/_form.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
<% end %>

<div class="inputs">
</div>


<%= form_tag(quotes_path) do %>

	<fieldset>
		<% @questions.each do |question| %>
		<legend><%= question.name %></legend>
			<% question.answers.each do |answer| %>
				<label class="radio">
				  <%= radio_button_tag "quote[questions[#{question.id}]]", answer.id, @quote.answers.include?(answer) %>
				  <!-- When we edit go to edit, the radio button are not showing their current values!!!-->
				  <%=answer.name%>
				</label>
				<%= hidden_field_tag :user_id, current_user.id %>
			<% end %>
	</fieldset>
		<% end %>

<hr>

	<div class="actions">
		<%= button_tag(type: "submit", class: "btn btn-success btn-default") do %>
		    Submit Quote <i class="icon-arrow-right"></i>
		<% end %>
	</div>

<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<div class="page-header">
  <h1>Listing My Quotes <small>Click to Edit or Remove Quotes</small></h1>
</div>

<p class="lead">Here you can view all your previous quotes to edit or delete them.  Or click to add a new quote!</p>

<%= link_to '<i class="icon-plus"></i> New Quote '.html_safe, new_quote_path, :class => "btn btn-large btn-success pull-left" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date Created</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.created_at.strftime("%b. %d %Y") %>

          <% if current_user.try(:admin?) %>
            <p><span class="label label-important"><%= quote.user.email %></span></p>
          <% end %>

        </td>
        <td><%= link_to 'Show', quote, :class => "btn btn-small" %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), :class => "btn btn-small btn-info" %></td>
        <td><%= link_to 'Delete', quote, :class => "btn btn-small btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/quotes/new.html.erb
<div class="page-header">
  <%= link_to 'Back', quotes_path, :class => "btn btn-inverse" %>
  <h1>New Quote</h1>
</div>

<p class="lead">To create a new quote fill out the questions below and submit your quote!</p>

<%= render 'form' %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', quotes_path, :class => "btn btn-inverse" %>

<div class="page-header">
  <h1>Quote From <%= @quote.created_at.strftime("%b. %d %Y") %></h1>
</div>

<p class="lead">To edit this quote click on the question you want to edit.</p>

<div class="alert alert-success">
	<h1>Quote Total: <strong>$<%=@total%></strong></h1>
</div>

<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Selection</th>
      <th>Value</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @quote.answers.each do |answer| %>
    <tr>
		
    <td><%= answer.question.name %></td>
		<!-- I can only get the question id to show here, but what I really need is the question name!  A question has many answers.  I think I need to create a lookup in the quotes controller but I'm not sure how to do this -->
		<td><%= answer.name %></td>
		<td><%= answer.value %></td>
		<td><%= link_to 'Edit', edit_quote_path(@quote, :anchor => "#{answer.id}"), :class => "btn btn-small btn-info" %></td>
	</tr>
	<% end %>

  </tbody>

</table>